[package]
name = "bip329"
version = "0.1.0"
edition = "2021"

[dependencies]

# ser/de
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

# error handling
thiserror = "1.0"

[dev-dependencies]
pretty_assertions = "1.4.0"
